//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int MAHOADON { get; set; }
        public int MA_HH { get; set; }
        public Nullable<double> UUDAI { get; set; }
        public Nullable<decimal> DONGIABAN { get; set; }
        public Nullable<int> SOLUONGHANGBAN { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
